### PR TITLE
Direction

### PR DESCRIPTION
**Pull request by darkdrgn2k**
Added cardinalDirectionAntenna to identify what kinda of antenna is currently running. 
cardinalDirection will continue to indicate exposure of location (ie east for eastward window)

On maps cardinalDirectionAntenna will take precedence over CardinalDirection for icon, however both will be displayed in details

Added None for cardinalDirection to identify datacenter like nodes that have no exposure at all.

Updated existing nodes to fit new schema changes

### CODE REVIEW

**Comment by Shrinks99** [comment]
Looks good to me, does this include data centre icons?

**Comment by darkdrgn2k** [comment]
No since this is the schema and node data only

**Comment by Shrinks99** [comment]
Got it, just checking to make sure I didn't miss that in a separate PR.

**Comment by darkdrgn2k** [comment]
Complementary PR for images and schema changes
https://github.com/tomeshnet/tomesh.net/pull/188

**Comment by darkdrgn2k** [comment]
The pr came as a result of a conversation about this problem:

I have a OMNI direction active node up and running, but i have a northern facing balcony, How do i define it in the node list.

Options proposed where

-  2 nodes, 1 active 1 proposed
- 1 node, specifying direction it could be if it wasnt omni
- using 2 attribute, one the direction the location is facing one that is the current antenna there

**Pull request merged**
