### PR TITLE
Initial schema

### PR DESCRIPTION
**Pull request by dcwalk**
Building on @Pedro-on-a-bike's initial [schema def'n](https://github.com/Pedro-on-a-bike/TOMeshNodeMap/blob/master/nodeListSchema.json), made a small suggestion about the name (to "Toronto Mesh" -- love my style guidelines).

We should discuss a few more points here, in particular I'm thinking about some of the guidelines around types and stuff? (http://json-ld.org/spec/latest/json-ld-api-best-practices/)

Also, I'm not super familiar with how schemas are published in a repo, etc.. so anyone got some best practices? 

I'm thinking of this example as the only one I was aware of:
https://github.com/postmanlabs/schemas/tree/develop/json/collection

### CODE REVIEW

**Comment by dcwalk** [comment]
Dropping this here: https://google.github.io/styleguide/jsoncstyleguide.xml#Property_Name_Format

**Comment by darkdrgn2k** [comment]
two suggestions

1) Contact data - Perhaps an email or something this way it would allow for a person who COULD link with a possible node to contact that person and start working on it.  

2) Maybe some dates - I think in the long term possible a date added or created or even approved would be useful to "prune" potential old locations that would no longer be viable.

**Comment by dcwalk** [comment]
Really good points @darkdrgn2k! cc @Pedro-on-a-bike or @benhylau et al., any thoughts before I charge ahead?

**Comment by Pedro-on-a-bike** [comment]
For the cardinal directions, right now I only have North, South, East, West. But on the recent list update, I included North East, South West, etc. Need to update the schema to allow this naming and more accurate description of the cardinal directions. Should also include omni if its 360 degrees.

I fine if people want to add their contact, however I don't think it should be a must.

**Comment by darkdrgn2k** [comment]
Only other thing I was toying with is possibly Elevation. Because we live in a 3d world this might be interesting to look at.  I mean 10th floor is 10th floor, unless you in a valley.  The height from ground level can be guesstimated using like 10 or 11ft per floor + google's geocode data. If done well you can even put together a directional calculator between two node (point your antenna at  X  degrees at Y  degrees Elevation

But on the other hand perhaps that can be done on the back end during evaluation of a possible link. But at least the idea is out there now for your scrutiny :)

**Comment by darkdrgn2k** [comment]
> I fine if people want to add their contact, however I don't think it should be a must.
I just worry that there may be need for communication with a node's owner in the future, at least a handle or something!

Last thing you want is some one to upload 1000 node points that are just random points and no way of contacting them.  I mean if your pushing the data in via GIT there is some sort of identity already there...

**Comment by darkdrgn2k** [comment]
> Should also include omni if its 360 degrees.

@Pedro-on-a-bike Just a point of clarification, in your node list currently you have "none" is that the same as "omni"

**Comment by Pedro-on-a-bike** [comment]
Well in general, we shouldn't be allowing a user to be uploading 1000s of points without some checks. This is one of the security concerns when you open a form to the public. This is also one of the reasons why I'm not in a rush to creating a list that can be modified by the public, especially since we don't even have one node up and active. We're a small community. Users that come across TOMesh end up on the chat and we can work with individually. We need to design for the order of magnitude that we can service at the moment: 1, 10, 100, 1000, 10000, etc.

As for elevation, it's going to be difficult to collect that data accurately. The main reason for elevation is for the directional antennas. It will be an issue to aim two antennas at each other if one is on the 3rd and the other on the 17th. For most of us, it will suffice to have their lat, long and floor data. If we really need elevation, as you suggested, we can work the back end.

"none" was no balcony. "omni" is for 360. But you bring up a good point. I was originally putting the data together in terms of their balcony, but someone could put their antenna by the window. I'll have to see if I can update the list to change "none" to a proper direction.

**Comment by darkdrgn2k** [comment]
What about BAND, 5ghz vs 2.4gz vs dualband.?

**Comment by dcwalk** [comment]
Talking at the library today with @garrying, @darkdrgn2k @Shrinks99, we've hashed out Stage 1:

- name
- longitude
- latitude
- IPv6
- cardinalDirectory
- status (proposed | active)

**Comment by dcwalk** [comment]
Awesome @garrying :)

**Pull request merged**
