### PR TITLE
nodeList.json -> tomeshnet-node-list.json

### PR DESCRIPTION
**Pull request by makeworld-the-better-one**

### CODE REVIEW

**Review by benhylau — APPROVED** [review]

**Comment by makeworld-the-better-one** [comment]
@darkdrgn2k Please approve when the dependent services are ready to go.

**Comment by darkdrgn2k** [comment]
I dont care

But it sounds like the redudnet department of redundancy.
tomesh.net/node-list/tomeshnet-node-list.json

but i guess it works as an isolated item

**Review by darkdrgn2k — APPROVED** [review]

**Comment by makeworld-the-better-one** [comment]
Thanks, merged. This may break the website.

**Comment by makeworld-the-better-one** [comment]
Thanks, merged. This may break the website.

**Pull request merged**
